### ISSUE TITLE
Fix box-sizing declaration

### ISSUE THREAD

**Issue by boriskaiser** [gulpaticjs/gulpatic#1]
https://github.com/gulpaticjs/gulpatic/blob/master/app/src/styles/styles.scss#L5-L10

Add  `&`:
```scss
* {
  &,
  &:before,
  &:after {
    box-sizing: inherit;
  }
}
```
